[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run build", "cd backend && npx prisma migrate deploy"]

[start]
cmd = "cd backend && npm run deploy"
