[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPaths = ["backend-rs/**"]

[deploy]
# Remove startCommand to use Dockerfile CMD with debug logging
# startCommand = "/usr/local/bin/backend-rs"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
