#!/bin/bash
echo "🧪 Testing Backend API..."
echo ""
echo "1. Health Check:"
curl -s https://perfect-happiness-production.up.railway.app/api/health | jq . || echo "❌ Failed"
echo ""
echo ""
echo "2. Events API:"
curl -s https://perfect-happiness-production.up.railway.app/api/events | jq . || echo "❌ Failed"
echo ""
echo ""
echo "3. Articles API:"
curl -s https://perfect-happiness-production.up.railway.app/api/articles | jq . || echo "❌ Failed"
echo ""
echo ""
echo "4. Categories API:"
curl -s https://perfect-happiness-production.up.railway.app/api/categories | jq . || echo "❌ Failed"
echo ""

